# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicationService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicationService.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18replicationService.proto\"%\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\t\"\x14\n\x12ReplicationRequest\"A\n\x13ReplicationResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t2\xa8\x01\n\x12ReplicationService\x12\x35\n\x04sync\x12\x13.ReplicationRequest\x1a\x14.ReplicationResponse\"\x00\x30\x01\x12\x1f\n\x06\x64\x65lete\x12\x08.Request\x1a\t.Response\"\x00\x12\x1c\n\x03put\x12\x08.Request\x1a\t.Response\"\x00\x12\x1c\n\x03get\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Request.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Request.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=65,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Response.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)


_REPLICATIONREQUEST = _descriptor.Descriptor(
  name='ReplicationRequest',
  full_name='ReplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=114,
)


_REPLICATIONRESPONSE = _descriptor.Descriptor(
  name='ReplicationResponse',
  full_name='ReplicationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ReplicationResponse.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='ReplicationResponse.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ReplicationResponse.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ReplicationRequest'] = _REPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['ReplicationResponse'] = _REPLICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'replicationService_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'replicationService_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

ReplicationRequest = _reflection.GeneratedProtocolMessageType('ReplicationRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONREQUEST,
  __module__ = 'replicationService_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationRequest)
  ))
_sym_db.RegisterMessage(ReplicationRequest)

ReplicationResponse = _reflection.GeneratedProtocolMessageType('ReplicationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONRESPONSE,
  __module__ = 'replicationService_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationResponse)
  ))
_sym_db.RegisterMessage(ReplicationResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ReplicationServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.sync = channel.unary_stream(
          '/ReplicationService/sync',
          request_serializer=ReplicationRequest.SerializeToString,
          response_deserializer=ReplicationResponse.FromString,
          )
      self.delete = channel.unary_unary(
          '/ReplicationService/delete',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.put = channel.unary_unary(
          '/ReplicationService/put',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.get = channel.unary_unary(
          '/ReplicationService/get',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )


  class ReplicationServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def sync(self, request, context):
      """Master/Slave Sync operation 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
      """Operations on the db 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def put(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'sync': grpc.unary_stream_rpc_method_handler(
            servicer.sync,
            request_deserializer=ReplicationRequest.FromString,
            response_serializer=ReplicationResponse.SerializeToString,
        ),
        'delete': grpc.unary_unary_rpc_method_handler(
            servicer.delete,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'put': grpc.unary_unary_rpc_method_handler(
            servicer.put,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'get': grpc.unary_unary_rpc_method_handler(
            servicer.get,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaReplicationServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def sync(self, request, context):
      """Master/Slave Sync operation 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def delete(self, request, context):
      """Operations on the db 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def put(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def get(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaReplicationServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def sync(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Master/Slave Sync operation 
      """
      raise NotImplementedError()
    def delete(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Operations on the db 
      """
      raise NotImplementedError()
    delete.future = None
    def put(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    put.future = None
    def get(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    get.future = None


  def beta_create_ReplicationService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('ReplicationService', 'delete'): Request.FromString,
      ('ReplicationService', 'get'): Request.FromString,
      ('ReplicationService', 'put'): Request.FromString,
      ('ReplicationService', 'sync'): ReplicationRequest.FromString,
    }
    response_serializers = {
      ('ReplicationService', 'delete'): Response.SerializeToString,
      ('ReplicationService', 'get'): Response.SerializeToString,
      ('ReplicationService', 'put'): Response.SerializeToString,
      ('ReplicationService', 'sync'): ReplicationResponse.SerializeToString,
    }
    method_implementations = {
      ('ReplicationService', 'delete'): face_utilities.unary_unary_inline(servicer.delete),
      ('ReplicationService', 'get'): face_utilities.unary_unary_inline(servicer.get),
      ('ReplicationService', 'put'): face_utilities.unary_unary_inline(servicer.put),
      ('ReplicationService', 'sync'): face_utilities.unary_stream_inline(servicer.sync),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ReplicationService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('ReplicationService', 'delete'): Request.SerializeToString,
      ('ReplicationService', 'get'): Request.SerializeToString,
      ('ReplicationService', 'put'): Request.SerializeToString,
      ('ReplicationService', 'sync'): ReplicationRequest.SerializeToString,
    }
    response_deserializers = {
      ('ReplicationService', 'delete'): Response.FromString,
      ('ReplicationService', 'get'): Response.FromString,
      ('ReplicationService', 'put'): Response.FromString,
      ('ReplicationService', 'sync'): ReplicationResponse.FromString,
    }
    cardinalities = {
      'delete': cardinality.Cardinality.UNARY_UNARY,
      'get': cardinality.Cardinality.UNARY_UNARY,
      'put': cardinality.Cardinality.UNARY_UNARY,
      'sync': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'ReplicationService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
